name: CommandBlackList
version: '${project.version}'
main: org.reuac.commandblacklist.CommandBlackList
commands:
  commandblacklist:
    description: "commandblacklist"
    aliases: cblist
    permission: commandblacklist.main